spring.application.name=kursach
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url = jdbc:postgresql://localhost:5432/postgres
spring.datasource.username = postgres
spring.datasource.password = postgres
jwt.secret = drs5JOG/jz5nQT9iqVIj9DiJINw5Abwodz7IzoUmahU=
logging.level.org.springframework.web = DEBUG
logging.level.org.springframework.security = DEBUG
