spring.application.name=station-service
server.port = 0

spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:postgresql://localhost:5432/station_service-DB
spring.datasource.username=postgres
spring.datasource.password=postgres

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG

eureka.client.service-url.default-zone=http://localhost:8761/eureka

geocoder.api.key=bb79cde2-9ae8-4196-be84-7637e73bd262
geocoder.api.url=https://geocode-maps.yandex.ru/1.x/
