CREATE TABLE IF NOT EXISTS order_statuses
(
    status_code VARCHAR(255) NOT NULL,
    status_name VARCHAR(255),
    CONSTRAINT pk_order_statuses PRIMARY KEY (status_code)
);

CREATE TABLE IF NOT EXISTS orders
(
    orders_id  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    vehicle_id BIGINT,
    status     VARCHAR(255) NOT NULL,
    station_id BIGINT,
    client_id  UUID,
    CONSTRAINT pk_orders PRIMARY KEY (orders_id)
);

CREATE TABLE IF NOT EXISTS order_services
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    service_id     BIGINT NOT NULL,
    service_name   VARCHAR(255),
    price_at_order NUMERIC(10, 2) NOT NULL,
    order_id       BIGINT NOT NULL,
    CONSTRAINT pk_order_services PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS orders_workers
(
    order_id  BIGINT NOT NULL,
    worker_id UUID NOT NULL,
    CONSTRAINT pk_orders_workers PRIMARY KEY (order_id, worker_id)
);

ALTER TABLE orders
    ADD CONSTRAINT fk_orders_on_status FOREIGN KEY (status) REFERENCES order_statuses (status_code);

ALTER TABLE order_services
    ADD CONSTRAINT fk_order_services_on_order FOREIGN KEY (order_id) REFERENCES orders (orders_id) ON DELETE CASCADE;

ALTER TABLE orders_workers
    ADD CONSTRAINT fk_orders_workers_on_order FOREIGN KEY (order_id) REFERENCES orders (orders_id) ON DELETE CASCADE;