CREATE TABLE payments(
    payment_id UUID,
    order_id BIGINT NOT NULL,
    amount DECIMAL NOT NULL,
    external_id VARCHAR(150),
    status VARCHAR(50) NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL ,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    confirmation_url VARCHAR(200),
    CONSTRAINT pk_payments PRIMARY KEY (payment_id)
);

CREATE TABLE outbox_events(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY ,
    event_id UUID UNIQUE NOT NULL,
    exchange VARCHAR(100) NOT NULL ,
    routing_key VARCHAR(100) NOT NULL ,
    payload TEXT NOT NULL ,
    status VARCHAR(50) NOT NULL ,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL
);

CREATE INDEX idx_outbox_status_created ON outbox_events(status,created_at)

