server.port = 0
spring.application.name=user-service


spring.jpa.hibernate.ddl-auto=update
spring.datasource.url = jdbc:postgresql://localhost:5432/user_service-DB
spring.datasource.username = postgres
spring.datasource.password = postgres

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG

eureka.client.service-url.default-zone = http://localhost:8761/eureka

feign.client.config.order-service.connectTimeout = 2000
feign.client.config.order-service.readTimeout = 5000
