server.port = 0
spring.application.name=user-service


spring.jpa.hibernate.ddl-auto=update
spring.datasource.url = jdbc:postgresql://localhost:5432/user-service-DB
spring.datasource.username = postgres
spring.datasource.password = postgres

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.password=guest
spring.rabbitmq.username=guest

spring.rabbitmq.template.retry.enabled=true
spring.rabbitmq.template.retry.max-attempts=3
spring.rabbitmq.template.retry.initial-interval = 2000ms

spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-attempts=3
spring.rabbitmq.listener.simple.retry.initial-interval=2000


user.exchange.name = user.events

dead.letter.exchange.name=common.dlx

user.dlq.user-register=user-service.user-register.dlq

user.delete.routing.key = user.deleted
user.create.routing.key = user.created
user.update.routing.key = user.updated
user.register.routing.key=user.register

user.queue.registration=user-service.user-registered

station.exchange.name=station.events
station.delete.queue=user-service.station-deleted
station.delete.routing.key=station.deleted

user.dlq.station-delete=user-service.station-deleted.dlq

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG

eureka.client.service-url.default-zone = http://localhost:8761/eureka

feign.client.config.order-service.connectTimeout = 2000
feign.client.config.order-service.readTimeout = 5000

spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=2000ms

spring.cache.type=redis