spring.application.name=security-service
server.port=0

spring.jpa.hibernate.ddl-auto=update

spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/security-service-DB

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.template.retry.enabled=true
spring.rabbitmq.template.retry.max-attempts=3
spring.rabbitmq.template.retry.initial-interval = 2000ms

eureka.client.service-url.default-zone=http://localhost:8761/eureka
