CREATE TABLE IF NOT EXISTS roles
(
    role_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    role_name VARCHAR(255),
    CONSTRAINT roles_pkey PRIMARY KEY (role_id)
);

CREATE TABLE IF NOT EXISTS users
(
    user_id       UUID NOT NULL,
    email         VARCHAR(255),
    user_name     VARCHAR(255),
    password_hash VARCHAR(255),
    station_id    BIGINT,
    role_id       BIGINT,
    CONSTRAINT users_pkey PRIMARY KEY (user_id),
    CONSTRAINT uk_users_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS vehicles
(
    vehicle_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    make       VARCHAR(255),
    model      VARCHAR(255),
    number     VARCHAR(255),
    user_id    UUID,
    CONSTRAINT vehicles_pkey PRIMARY KEY (vehicle_id),
    CONSTRAINT uk_vehicles_number UNIQUE (number)
);

ALTER TABLE users
    ADD CONSTRAINT fk_users_role FOREIGN KEY (role_id)
        REFERENCES roles (role_id) ON DELETE NO ACTION;

ALTER TABLE vehicles
    ADD CONSTRAINT fk_vehicles_user FOREIGN KEY (user_id)
        REFERENCES users (user_id) ON DELETE NO ACTION;