CREATE SEQUENCE IF NOT EXISTS users_user_id_seq START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE IF NOT EXISTS vehicles_vehicle_id_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE roles
(
    role_id   BIGINT NOT NULL,
    role_name VARCHAR(255),
    CONSTRAINT roles_pkey PRIMARY KEY (role_id)
);

CREATE TABLE users
(
    user_id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email         VARCHAR(255),
    user_name     VARCHAR(255),
    password_hash VARCHAR(255),
    station_id    BIGINT,
    role_id       BIGINT,
    CONSTRAINT users_pkey PRIMARY KEY (user_id)
);

CREATE TABLE vehicles
(
    vehicle_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    make       VARCHAR(255),
    model      VARCHAR(255),
    number     VARCHAR(255),
    user_id    BIGINT,
    CONSTRAINT vehicles_pkey PRIMARY KEY (vehicle_id)
);

ALTER TABLE users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);

ALTER TABLE vehicles
    ADD CONSTRAINT ukdt9xs92iuuwcietw5bh6wk0tw UNIQUE (number);

ALTER TABLE vehicles
    ADD CONSTRAINT fko4u5y92lt2sx8y2dc1bb9sewc FOREIGN KEY (user_id) REFERENCES users (user_id) ON DELETE NO ACTION;

ALTER TABLE users
    ADD CONSTRAINT fkp56c1712k691lhsyewcssf40f FOREIGN KEY (role_id) REFERENCES roles (role_id) ON DELETE NO ACTION;