spring.application.name=order-service
server.port=0

spring.profiles.active=dev

spring.config.import=optional:configserver:http://config_admin:config_secure_password@${CONFIG_SERVER_HOST:config-server}:8888

order.exchange = order.events

order.success.station.delete.routing.key = order.station.delete.success
order.failed.station.delete.routing.key = order.station.delete.failed