spring.application.name=order-service
server.port=0

spring.profiles.active=dev

spring.config.import=optional:configserver:http://config_admin:config_secure_password@localhost:8888

spring.cloud.config.fail-fast=true

resilience4j.circuitbreaker.configs.default.sliding-window-size=20
resilience4j.circuitbreaker.configs.default.failure-rate-threshold=50
resilience4j.circuitbreaker.configs.default.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.configs.default.permitted-number-of-calls-in-half-open-state=5

resilience4j.circuitbreaker.instances.stationServiceBreaker.base-config=default
resilience4j.circuitbreaker.instances.userServiceBreaker.base-config=default

feign.client.config.user-service.connect-timeout=2000
feign.client.config.user-service.read-timeout=3000

feign.client.config.station-service.connect-timeout=2000
feign.client.config.station-service.read-timeout=4000