CREATE TABLE IF NOT EXISTS roles
(
    role_id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    role_name VARCHAR(255) NOT NULL,
    CONSTRAINT pk_roles PRIMARY KEY (role_id),
    CONSTRAINT uc_roles_role_name UNIQUE (role_name)
);

CREATE TABLE IF NOT EXISTS users
(
    id           UUID         NOT NULL,
    email        VARCHAR(255) NOT NULL,
    password     VARCHAR(255) NOT NULL,
    workplace_id BIGINT,
    role_id      BIGINT       NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT fk_users_on_role FOREIGN KEY (role_id) REFERENCES roles (role_id);