CREATE TABLE IF NOT EXISTS station
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(255),
    latitude     NUMERIC(9, 6),
    longitude    NUMERIC(9, 6),
    address_text VARCHAR(255),
    CONSTRAINT station_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS service
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255),
    price      NUMERIC(10, 2),
    station_id BIGINT,
    CONSTRAINT service_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS station_orders
(
    station_id BIGINT NOT NULL,
    order_id   BIGINT NOT NULL
);

ALTER TABLE service
    ADD CONSTRAINT fk_service_station FOREIGN KEY (station_id)
        REFERENCES station (id) ON DELETE CASCADE;

ALTER TABLE station_orders
    ADD CONSTRAINT fk_station_orders_station FOREIGN KEY (station_id)
        REFERENCES station (id) ON DELETE CASCADE;